#pragma once

#define EE_HANDS

#define SERIAL_USART_FULL_DUPLEX
#define SERIAL_USART_TX_PIN GP0
#define SERIAL_USART_RX_PIN GP1

/* #define SPLIT_USB_TIMEOUT 2000 */
/* #define SPLIT_LAYER_STATE_ENABLE */
/* #define SERIAL_USART_SPEED 115200 */

#define SERIAL_DEBUG
#define SPLIT_WATCHDOG_ENABLE

#define TAPPING_TERM 200
#define WS2812_DI_PIN GP16
#define RGBLIGHT_LED_COUNT 1
#define RGBLIGHT_LIMIT_VAL 55

#define RGBLIGHT_LAYERS
#define RGBLIGHT_SPLIT
#define SPLIT_LAYER_STATE_ENABLE
