#pragma once

#define EE_HANDS
/* #define MASTER_LEFT */
/* #define MASTER_RIGHT */

#define SERIAL_USART_FULL_DUPLEX
#define SERIAL_USART_TX_PIN GP1
#define SERIAL_USART_RX_PIN GP0
#define SPLIT_USB_DETECT
/* #define SPLIT_USB_TIMEOUT 2000 */
/* #define SPLIT_LAYER_STATE_ENABLE */
/* #define SERIAL_USART_SPEED 115200 */
#define SERIAL_DEBUG
#define SPLIT_WATCHDOG_ENABLE

#define MATRIX_ROWS 8
#define MATRIX_COLS 10

#define TAPPING_TERM 200
/* #define FLOW_TAP_TERM 150 */
